### ISSUE TITLE
Make connect() and setupAndConnect() return a promise.

### ISSUE THREAD

**Issue by pkrs** [tinode/tinode-sdk-js#4]
Right now it's not possible since there isn't a message id passed/returned on the initial connect (there're other ways, but more they seem to be more ugly).

This will make much clearer division that all public methods on Tinode object return a promise so it's easy to chain them together. And callbacks can serve as a feedback to update UI.

Right now onConnect callback is used to signal that we can start Login() and next steps.

**Comment by or-else** [comment]
Done, see https://github.com/tinode/chat/commit/9e193bfdb417acf1c7c5487414684f48a79e521a
